[google_sheets]
creds_json = """{
  "type": "service_account",
  "project_id": "grandma-boy",
  "private_key_id": "xxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nABC\\nDEF\\n-----END PRIVATE KEY-----\\n",
  ...
}"""
